### ISSUE TITLE
[support] pointers on how to alter body on proxies request to server?

### ISSUE THREAD

**Issue by patcon** [argo/argo#58]
First off, thanks so much for the rad product!

Totally my fault here, but I'm going a little batty trying to sort this out, and would totally appreciate any pointers in the right direction :)

https://github.com/patcon/polis-api-proxy/blob/master/path_parameterization.js#L33

It's pretty messy, but I've intercepted POST requests, caught the body, and merged my changes in, but I can't seem to sort out the best way to "pass this along"..! :)

**Comment by kevinswiber** [comment]
Hi, @patcon!

I think setting `env.request.body` should work, though I'm not sure why you're pausing the stream.

Because `getBody` is asynchronous, you need to make sure `next(env)` is nested in the callback.  Otherwise, there will be a race condition on the event loop.  That might be what you're seeing here.

Cheers,

Kevin

**Comment by patcon** [comment]
AH. fml. thank you thank you thank you! i think that was it. was just getting ready to switch to node-http-proxy, so I really appreciate the help :)

**Comment by patcon** [comment]
Got it working! Thanks again!
